import type { VocabItem } from '../models/vocab';
import { word, tips } from './helpers';

export const vocabBatch30: VocabItem[] = [
  word('cycle', '순환', 1, 'noun',
    ['단절', '중단', '끊김', '일회성', '선형', '직선', '종말', '끝', '파괴', '해체'],
    tips({
      etymology: '그리스어 \'kyklos(원, 바퀴)\'에서 유래하여 제자리로 돌아오는 움직임을 뜻합니다.',
      visual: '화살표가 꼬리에 꼬리를 물고 원형으로 돌아가는 재활용 마크를 상상해 보세요.',
      soundAlike: '자전거를 뜻하는 \'바이시클(bicycle)\'의 뒷부분과 발음이 같아 바퀴의 회전을 연상시킵니다.',
      context: '자연의 계절 변화나 경제의 호황과 불황처럼 반복되는 패턴을 설명할 때 주로 쓰입니다.',
      synonymAntonym: '반복되는 sequence와 유사하며, 한 방향으로만 가는 linear 과정과는 반대됩니다.',
    }),
    {
      definition: 'A sequence of events that happen again and again in the same order.',
      synonyms: ['rotation', 'sequence', 'loop'],
      antonyms: ['interruption', 'stagnation', 'discontinuity'],
      exampleSentences: [
        { en: 'The natural water process is a continuous movement between the earth and the atmosphere.', ko: '자연적인 물의 순환은 지구와 대기 사이의 지속적인 움직임입니다.' },
        { en: 'Economists are studying the business patterns of boom and recession over the last decade.', ko: '경제학자들은 지난 10년 동안의 경기 호황과 불황의 순환 고리를 연구하고 있습니다.' },
      ],
    }
  ),
  word('dad', '아빠', 2, 'noun',
    ['엄마', '형제', '조부', '삼촌', '이웃', '선생', '친구', '동료', '낯선 사람', '타인'],
    tips({
      etymology: '어린아이가 아버지를 부를 때 내는 \'다다\' 소리에서 유래한 친근한 표현입니다.',
      visual: '넥타이를 매고 퇴근하며 웃으며 들어오는 아버지의 모습을 상상해 보세요.',
      soundAlike: '발음이 \'대드\'와 비슷하니, \'대\'단한 \'드\'라마 같은 우리 아빠라고 외워보세요.',
      context: '가정 내에서 아버지를 격식 없이 다정하게 부를 때 주로 사용합니다.',
      synonymAntonym: '격식 있는 표현인 father와 짝을 이루며, 반대 성별인 mom과 함께 기억하세요.',
    }),
    {
      definition: 'A male parent who is often addressed with affection by his children.',
      synonyms: ['father', 'papa', 'daddy'],
      antonyms: ['mom', 'mother', 'mummy'],
      exampleSentences: [
        { en: 'My father\'s friend asked me to call him by his first name instead of sir.', ko: '우리 아빠의 친구는 나에게 아저씨 대신 이름을 불러달라고 부탁하셨다.' },
        { en: 'The little boy ran to the door to greet his male parent after work.', ko: '어린 소년은 퇴근한 아빠를 맞이하기 위해 문으로 달려갔다.' },
      ],
    }
  ),
  word('dairy', '낙농장', 7, 'noun',
    ['공장', '창고', '슈퍼마켓', '식당', '양계장', '과수원', '논', '밭', '정육점', '제과점'],
    tips({
      etymology: '중세 영어 \'deierie\'에서 유래했으며, 젖을 짜는 여성을 뜻하는 \'deye\'와 장소를 뜻하는 \'-ry\'가 합쳐진 단어입니다.',
      visual: '푸른 초원에서 젖소들이 풀을 뜯고 있고, 갓 짠 우유 통이 가득 쌓여 있는 시골 목장을 상상해 보세요.',
      soundAlike: '매일 쓰는 일기인 \'diary\'와 철자가 비슷하니 주의하세요. \'ai\'가 들어간 dairy는 우유와 관련된 낙농장입니다.',
      context: '마트의 \'dairy section\'은 우유, 치즈, 요거트 같은 유제품을 파는 구역을 말합니다.',
      synonymAntonym: '우유를 생산하는 creamery와 유사하며, 식물성 제품만을 다루는 농장과는 대조적인 개념입니다.',
    }),
    {
      definition: 'An establishment where milk is kept, processed, or made into products like butter and cheese.',
      synonyms: ['creamery', 'milking shed', 'dairy farm'],
      antonyms: ['orchard', 'vineyard', 'fishery'],
      exampleSentences: [
        { en: 'The local dairy supplies fresh milk to the entire village every morning.', ko: '그 지역 낙농장은 매일 아침 마을 전체에 신선한 우유를 공급합니다.' },
        { en: 'We visited a large dairy to see how cheese is manufactured from scratch.', ko: '우리는 치즈가 처음부터 어떻게 제조되는지 보기 위해 큰 낙농장을 방문했습니다.' },
      ],
    }
  ),
  word('dam', '댐', 4, 'noun',
    ['운하', '수로', '강', '호수', '배수로', '터널', '다리', '제방', '둑', '수문'],
    tips({
      etymology: '고대 네덜란드어에서 유래하여 물의 흐름을 막는 둑이나 장벽을 의미하게 되었습니다.',
      visual: '거대한 콘크리트 벽이 엄청난 양의 강물을 가로막고 있는 웅장한 모습을 상상해 보세요.',
      soundAlike: '욕설인 \'damn\'과 발음이 같으므로 문맥을 통해 수자원 시설임을 구분해야 합니다.',
      context: '주로 수력 발전이나 홍수 조절, 농업용수 확보를 위한 토목 공사와 관련된 상황에서 쓰입니다.',
      synonymAntonym: 'barrier나 reservoir와 함께 기억하고, 물이 자유롭게 흐르는 stream과 대조해 보세요.',
    }),
    {
      definition: 'A massive structure constructed across a river or stream to restrict the flow of water and create a reservoir.',
      synonyms: ['barrier', 'embankment', 'reservoir'],
      antonyms: ['opening', 'outlet', 'waterfall'],
      exampleSentences: [
        { en: 'The government decided to build a new concrete structure to prevent seasonal flooding in the valley.', ko: '정부는 계곡의 계절적 홍수를 예방하기 위해 새로운 콘크리트 제방 시설을 건설하기로 결정했습니다.' },
        { en: 'Hydroelectric power is generated by the force of water falling from the top of the massive wall.', ko: '수력 발전은 거대한 벽의 꼭대기에서 떨어지는 물의 힘에 의해 생성됩니다.' },
      ],
    }
  ),
  word('damp', '축축한', 5, 'adjective',
    ['건조한', '바삭한', '딱딱한', '거친', '매끄러운', '투명한', '희미한', '단단한', '무거운', '가벼운'],
    tips({
      etymology: '중세 저지 독일어 \'damp\'에서 유래했으며, 원래는 \'증기\'나 \'연기\'를 뜻하던 단어가 습기를 머금은 상태로 변했습니다.',
      visual: '비가 그친 뒤 덜 마른 빨래나 아침 이슬이 맺힌 눅눅한 흙바닥을 상상해 보세요.',
      soundAlike: '발음이 \'댐\'과 비슷합니다. 댐(dam) 주변은 물기가 많아 항상 축축하다(damp)고 연상하세요.',
      context: '지하실의 눅눅한 공기나 운동 후 땀에 젖은 티셔츠를 묘사할 때 자주 쓰입니다.',
      synonymAntonym: 'moist와 유사하지만 damp는 종종 불쾌하거나 원치 않는 눅눅함을 표현할 때 더 자주 쓰이며, dry와는 정반대입니다.',
    }),
    {
      definition: 'slightly wet in a way that is often unpleasant or uncomfortable',
      synonyms: ['moist', 'humid', 'clammy'],
      antonyms: ['dry', 'arid', 'parched'],
      exampleSentences: [
        { en: 'The clothes were still damp because it had been raining all day.', ko: '하루 종일 비가 내려서 옷이 여전히 축축했다.' },
        { en: 'We had to sleep in a damp tent, which was very uncomfortable.', ko: '우리는 눅눅한 텐트에서 자야 했는데, 그것은 매우 불편했다.' },
      ],
    }
  ),
  word('dare', '감히 하다', 6, 'verb',
    ['회피하다', '망설이다', '순응하다', '포기하다', '조심하다', '두려워하다', '무시하다', '복종하다', '지연시키다', '거절하다'],
    tips({
      etymology: '고대 영어 \'durran\'에서 유래하여 \'용기를 내다\' 혹은 \'대담해지다\'라는 의미를 뿌리에 두고 있습니다.',
      visual: '절벽 끝에서 뛰어내리기 직전의 대담한 도전자의 모습을 상상해 보세요.',
      soundAlike: '발음이 \'대어(大魚)\'와 비슷하죠? 큰 물고기를 잡으려면 \'감히\' 위험을 무릅써야 합니다.',
      context: '주로 부정문이나 의문문에서 \'어떻게 감히 그럴 수 있어?\'라는 강한 어조로 자주 쓰입니다.',
      synonymAntonym: 'challenge와 같이 도전적인 태도를 나타내며, 반대로 fear는 시도조차 못 하는 두려움을 뜻합니다.',
    }),
    {
      definition: 'to be brave enough to do something difficult or dangerous',
      synonyms: ['challenge', 'venture', 'confront'],
      antonyms: ['avoid', 'dodge', 'refrain'],
      exampleSentences: [
        { en: 'He did not believe anyone would be brave enough to challenge his authority.', ko: '그는 누구도 감히 자신의 권위에 도전할 만큼 용감할 것이라고 믿지 않았다.' },
        { en: 'How can you show such disrespect to your parents after all they have done?', ko: '부모님이 해주신 모든 일에도 불구하고 어떻게 감히 그렇게 무례하게 행동할 수 있니?' },
      ],
    }
  ),
  word('darling', '사랑하는 사람', 7, 'noun',
    ['낯선 사람', '원수', '경쟁자', '동료', '지인', '이웃', '손님', '타인', '외인', '적'],
    tips({
      etymology: '고대 영어 deorling에서 유래했으며, \'귀중한\'을 뜻하는 dear에 지소사 -ling이 붙어 만들어진 단어입니다.',
      visual: '연인이나 아이에게 다정하게 말을 건네며 미소 짓는 따뜻한 장면을 상상해 보세요.',
      soundAlike: '발음이 \'달링\'과 비슷하므로, 밤하늘의 소중하고 아름다운 \'달\'처럼 빛나는 사람이라고 연상해 보세요.',
      context: '주로 배우자, 연인, 혹은 아주 아끼는 자녀를 부를 때 애칭으로 자주 사용됩니다.',
      synonymAntonym: 'beloved와 같은 유의어와 함께 외우고, 적대적인 관계인 enemy와 대조해 보세요.',
    }),
    {
      definition: 'A person who is very much loved, cherished, or favorite to someone else.',
      synonyms: ['beloved', 'sweetheart', 'dearest'],
      antonyms: ['enemy', 'adversary', 'rival'],
      exampleSentences: [
        { en: 'Goodnight, my darling, I will see you in the morning.', ko: '잘 자요, 내 사랑, 아침에 만나요.' },
        { en: 'She has always been the darling of the local theater community.', ko: '그녀는 항상 지역 연극계의 총아였습니다.' },
      ],
    }
  ),
  word('dash', '돌진', 4, 'noun',
    ['정지', '지연', '후퇴', '대기', '감속', '침체', '휴식', '방관', '고착', '완만'],
    tips({
      etymology: '중세 영어 dasken에서 유래하여 \'세게 치다\' 혹은 \'갑자기 움직이다\'라는 역동적인 움직임을 담고 있습니다.',
      visual: '100미터 달리기 선수가 출발 신호와 함께 총알처럼 튀어나가는 장면을 상상해 보세요.',
      soundAlike: '대시(dash)라는 발음이 무언가를 \'대차게\' 밀어붙이는 느낌과 비슷하다고 생각하면 쉽습니다.',
      context: '주로 급하게 어디론가 가야 할 때나, 요리에서 조미료를 아주 조금 넣을 때도 사용됩니다.',
      synonymAntonym: 'rush와 유사하며, 반대로 천천히 움직이는 dawdle이나 정지 상태인 halt와 대비됩니다.',
    }),
    {
      definition: 'a quick, sudden movement toward a particular direction or a brief race',
      synonyms: ['sprint', 'rush', 'bolt'],
      antonyms: ['stroll', 'crawl', 'halt'],
      exampleSentences: [
        { en: 'The cat made a sudden dash for the open door as soon as it saw a chance.', ko: '그 고양이는 기회를 포착하자마자 열린 문을 향해 갑자기 돌진했다.' },
        { en: 'We had to make a mad dash to the station to catch the last train.', ko: '우리는 막차를 타기 위해 역으로 미친 듯이 달려가야만 했다.' },
      ],
    }
  ),
  word('date', '날짜', 3, 'noun',
    ['시간', '장소', '이름', '숫자', '금액', '단위', '색깔', '크기', '재료', '방식'],
    tips({
      etymology: '라틴어 \'datum(주어진 것)\'에서 유래하여, 문서가 작성된 \'주어진 시간\'을 의미하게 되었습니다.',
      visual: '달력의 특정 칸에 빨간색 동그라미가 쳐져 있는 모습을 상상해 보세요.',
      soundAlike: '달콤한 \'대추(date)\'를 먹으며 연인과 만날 약속 날짜를 잡는 장면을 연상하세요.',
      context: '일상에서는 달력상의 날을 의미하기도 하지만, 연인 사이의 로맨틱한 만남을 뜻하기도 합니다.',
      synonymAntonym: 'day와 유사하지만 더 구체적인 시점을 뜻하며, 영원함을 뜻하는 eternity와는 대조적입니다.',
    }),
    {
      definition: 'A specific day of the month or year, or a prearranged social engagement with another person.',
      synonyms: ['appointment', 'occasion', 'rendezvous'],
      antonyms: ['eternity', 'timelessness', 'age'],
      exampleSentences: [
        { en: 'Please write today\'s day and month at the top of the application form.', ko: '신청서 상단에 오늘 날짜를 적어 주세요.' },
        { en: 'He was nervous because it was his first romantic outing with her.', ko: '그녀와의 첫 데이트였기 때문에 그는 매우 긴장했다.' },
      ],
    }
  ),
  word('daughter', '딸', 1, 'noun',
    ['아들', '부모', '형제', '조부', '친척', '친구', '이웃', '동료', '낯선 사람', '타인'],
    tips({
      etymology: '고대 영어 \'dohtor\'에서 유래했으며, 인도유럽어족에서 \'젖을 짜는 사람\'이라는 의미의 어근과 연결되기도 합니다.',
      visual: '어린 소녀가 아빠의 손을 잡고 공원을 산책하며 웃고 있는 다정한 부녀의 모습을 상상해 보세요.',
      soundAlike: '\'도터\'라고 발음되는데, \'도\'망가는 \'터\'프한 딸아이의 뒷모습을 연상하며 외워보세요.',
      context: '가족 관계를 설명할 때 여성 자녀를 지칭하며, 아들을 뜻하는 son과 짝을 이루어 자주 쓰입니다.',
      synonymAntonym: '여성 자녀를 뜻하는 female child와 유사하며, 반대되는 성별의 자녀는 son입니다.',
    }),
    {
      definition: 'A female offspring in relation to her parents.',
      synonyms: ['female child', 'girl', 'offspring'],
      antonyms: ['son', 'father', 'mother'],
      exampleSentences: [
        { en: 'They are very proud of their youngest child\'s academic achievements.', ko: '그들은 막내딸의 학업 성취를 매우 자랑스러워합니다.' },
        { en: 'She looks exactly like her mother when she smiles.', ko: '그녀는 웃을 때 자신의 어머니와 똑 닮았습니다.' },
      ],
    }
  ),
  word('dawn', '새벽', 5, 'noun',
    ['황혼', '정오', '자정', '일몰', '오후', '저녁', '심야', '낮잠', '계절', '안개'],
    tips({
      etymology: '고대 영어 \'dagian(날이 밝다)\'에서 유래하여 어둠이 걷히고 빛이 시작되는 시점을 뜻합니다.',
      visual: '지평선 너머로 붉은 해가 아주 조금씩 고개를 내밀며 하늘이 밝아지는 풍경을 상상해 보세요.',
      soundAlike: '\'돈(dawn)\'을 벌기 위해 남들보다 일찍 \'새벽\'부터 일어나는 부지런한 모습을 연상하세요.',
      context: '단순히 시간대뿐만 아니라 \'새로운 시대의 서막\'처럼 어떤 일의 시작을 비유할 때도 자주 쓰입니다.',
      synonymAntonym: '해돋이를 뜻하는 sunrise와 비슷하며, 해가 지는 dusk와는 반대되는 개념입니다.',
    }),
    {
      definition: 'The first appearance of light in the sky before sunrise or the very beginning of a new period.',
      synonyms: ['daybreak', 'sunrise', 'inception'],
      antonyms: ['dusk', 'sunset', 'twilight'],
      exampleSentences: [
        { en: 'The farmers woke up at dawn to begin their work in the fields.', ko: '농부들은 들판에서 일을 시작하기 위해 새벽에 일어났다.' },
        { en: 'The invention of the internet marked the dawn of a new era in communication.', ko: '인터넷의 발명은 통신에 있어 새로운 시대의 시작을 알렸다.' },
      ],
    }
  ),
  word('dead', '죽은', 2, 'adjective',
    ['살아있는', '활기찬', '신선한', '성장하는', '존재하는', '움직이는', '깨어있는', '건강한', '유효한', '활동적인'],
    tips({
      etymology: '고대 영어 \'dead\'에서 유래했으며, \'생명이 다한\' 상태를 뜻하는 게르만어 계열의 뿌리를 가지고 있습니다.',
      visual: '시든 꽃이나 멈춰버린 시계의 태엽처럼 생명력이나 움직임이 완전히 사라진 모습을 상상해 보세요.',
      soundAlike: '\'데드\'라고 발음하며, 게임에서 캐릭터가 쓰러질 때 나오는 \'Game Over\' 화면과 연결하면 기억하기 쉽습니다.',
      context: '생물학적인 죽음뿐만 아니라, 배터리가 방전되었거나 기계가 작동하지 않을 때도 자주 쓰입니다.',
      synonymAntonym: '살아있는 상태인 alive와 반대되며, 격식 있는 표현인 deceased와 함께 기억하면 좋습니다.',
    }),
    {
      definition: 'no longer living or functioning; deprived of life',
      synonyms: ['lifeless', 'deceased', 'expired'],
      antonyms: ['alive', 'living', 'animated'],
      exampleSentences: [
        { en: 'The fallen leaves on the ground were brown and dead.', ko: '바닥에 떨어진 잎들은 갈색으로 변해 죽어 있었다.' },
        { en: 'I couldn\'t call you because my phone was dead.', ko: '내 휴대전화 배터리가 나가서 너에게 전화할 수 없었어.' },
      ],
    }
  ),
  word('deal', '거래', 6, 'noun',
    ['거절', '파기', '취소', '무효', '단절', '불협의', '갈등', '분쟁', '해지', '포기'],
    tips({
      etymology: '고대 영어 \'dæl\'에서 유래하여 \'부분\'이나 \'나누다\'라는 의미에서 서로 몫을 나누는 \'거래\'로 발전했습니다.',
      visual: '비즈니스 정장을 입은 두 사람이 악수를 하며 계약서에 서명하는 장면을 상상해 보세요.',
      soundAlike: '카지노 딜러(dealer)가 카드를 나누어 주며 게임을 시작하는(deal) 상황을 떠올리면 쉽습니다.',
      context: '비즈니스 협상뿐만 아니라 \'a great deal of\'처럼 양이 많음을 나타낼 때도 자주 쓰입니다.',
      synonymAntonym: 'agreement와 유사하며, 계약이 성립되지 않은 disagreement나 refusal과는 반대되는 개념입니다.',
    }),
    {
      definition: 'an agreement entered into by two or more parties for their mutual benefit, especially in a business or political context',
      synonyms: ['agreement', 'transaction', 'bargain'],
      antonyms: ['disagreement', 'denial', 'refusal'],
      exampleSentences: [
        { en: 'The two companies finally signed a deal to cooperate on the new project.', ko: '두 회사는 마침내 새로운 프로젝트에 협력하기로 하는 거래 계약을 체결했습니다.' },
        { en: 'If you buy three shirts at once, the shopkeeper will give you a better deal.', ko: '셔츠 세 장을 한꺼번에 사면 가게 주인이 더 좋은 조건으로 거래해 줄 것입니다.' },
      ],
    }
  ),
  word('death', '죽음', 3, 'noun',
    ['탄생', '생명', '생존', '회생', '부활', '성장', '발달', '건강', '활력', '생기'],
    tips({
      etymology: '고대 영어 \'death\'에서 유래했으며, 동사 \'die\'의 명사형으로 생명이 멈춘 상태를 뜻합니다.',
      visual: '촛불이 서서히 꺼지며 연기만 남은 고요한 장면을 상상해 보세요.',
      soundAlike: '\'데스\' 발음이 \'데이다(화상)\'와 비슷하죠? 뜨거운 불에 데어 생명이 위태로운 상황을 연상해 보세요.',
      context: '뉴스나 역사 책에서 인물의 생애를 마감할 때나 비극적인 사건을 다룰 때 자주 등장합니다.',
      synonymAntonym: '생명을 뜻하는 life와 정반대 개념이며, 격식 있는 표현으로는 decease라고도 합니다.',
    }),
    {
      definition: 'the permanent end of all biological functions that sustain a living organism',
      synonyms: ['demise', 'passing', 'decease'],
      antonyms: ['birth', 'life', 'existence'],
      exampleSentences: [
        { en: 'The sudden passing of the king led to a period of national mourning.', ko: '왕의 갑작스러운 죽음은 국가적인 애도 기간으로 이어졌다.' },
        { en: 'Scientists are studying the biological processes that occur after the cessation of life.', ko: '과학자들은 생명이 멈춘 후 발생하는 생물학적 과정들을 연구하고 있다.' },
      ],
    }
  ),
  word('decade', '10년', 7, 'noun',
    ['1년', '한 달', '일주일', '하루', '한 시간', '반세기', '세기', '순간', '영원', '단기'],
    tips({
      etymology: '그리스어 \'deka\'에서 유래했으며, 이는 숫자 10을 의미합니다.',
      visual: '달력 10장이 겹쳐져 있는 모습이나 숫자 10이 크게 적힌 타임캡슐을 상상해 보세요.',
      soundAlike: '\'데케이드\'라고 발음하며, \'대(大)기대\'했던 10년의 세월로 기억하면 쉽습니다.',
      context: '역사적 변화나 개인의 성장 과정을 설명할 때 10년 단위의 긴 시간을 나타냅니다.',
      synonymAntonym: '10년을 뜻하는 decennium과 유사하며, 100년을 뜻하는 century와 대조됩니다.',
    }),
    {
      definition: 'A span of time consisting of ten consecutive years.',
      synonyms: ['decennium', 'ten-year period', 'ten years'],
      antonyms: ['moment', 'instant', 'second'],
      exampleSentences: [
        { en: 'The technology has advanced significantly over the past ten-year span.', ko: '지난 10년 동안 기술은 상당히 발전했습니다.' },
        { en: 'It took nearly ten years for the company to become profitable.', ko: '그 회사가 수익을 내기까지 거의 10년이 걸렸습니다.' },
      ],
    }
  ),
  word('decay', '쇠퇴하다', 4, 'verb',
    ['번영하다', '성장하다', '복구하다', '보존하다', '건설하다', '유지하다', '개선하다', '부활하다', '강화하다', '창조하다'],
    tips({
      etymology: '라틴어 \'decidere\'에서 유래되었으며, \'de(아래로)\'와 \'cadere(떨어지다)\'가 결합되어 상태가 나빠짐을 의미합니다.',
      visual: '오래된 나무가 썩어서 흙으로 돌아가거나 화려했던 건물이 무너져 내리는 모습을 상상해 보세요.',
      soundAlike: '\'디케이\'라고 발음하며, 이빨이 \'뒤게(디게)\' 아플 정도로 썩어가는 상황을 연상해 보세요.',
      context: '주로 유기물이 부패하거나, 국가의 국력 또는 도덕성이 점차 약해지는 상황에서 자주 쓰입니다.',
      synonymAntonym: '부패를 뜻하는 rot과 유사하며, 번영을 뜻하는 flourish와는 반대되는 개념입니다.',
    }),
    {
      definition: 'to gradually become bad or weak in quality, or to be destroyed by natural processes',
      synonyms: ['rot', 'deteriorate', 'decline'],
      antonyms: ['flourish', 'thrive', 'grow'],
      exampleSentences: [
        { en: 'The wooden structure began to crumble as it started to rot over the years.', ko: '그 나무 구조물은 수년에 걸쳐 부식되기 시작하면서 허물어지기 시작했다.' },
        { en: 'Economic instability caused the once-great empire to fall into a state of ruin.', ko: '경제적 불안정은 한때 위대했던 제국을 쇠퇴의 길로 접어들게 만들었다.' },
      ],
    }
  ),
  word('decide', '결정하다', 1, 'verb',
    ['선택하다', '요청하다', '설명하다', '관리하다', '보완하다', '분석하다', '정리하다', '적용하다', '반복하다', '망설이다'],
    tips({
      etymology: '라틴어 \'decidere\'에서 유래했으며, \'de(자르다)\'와 \'caedere(끊다)\'가 합쳐져 고민을 싹둑 잘라내고 결론을 내린다는 의미입니다.',
      visual: '갈림길 앞에서 한쪽 길을 가리키며 확신에 찬 표정을 짓는 여행자의 모습을 상상해 보세요.',
      soundAlike: '\'디사이드\' 발음이 \'뒤(de)를 사이(side) 좋게 끊다\'라고 연상하여 미련 없이 결정하는 장면을 떠올려 보세요.',
      context: '식당에서 메뉴를 고르거나 인생의 중요한 진로를 정할 때처럼 여러 선택지 중 하나를 확정할 때 사용합니다.',
      synonymAntonym: '결심을 굳히는 determine과 비슷하지만, 결정을 미루는 hesitate와는 반대되는 개념입니다.',
    }),
    {
      definition: 'to make a final choice or come to a resolution after considering various possibilities',
      synonyms: ['determine', 'resolve', 'settle'],
      antonyms: ['hesitate', 'waver', 'postpone'],
      exampleSentences: [
        { en: 'It was difficult to choose, but I finally had to pick which car to buy.', ko: '선택하기 어려웠지만, 결국 어떤 차를 살지 결정해야만 했다.' },
        { en: 'The committee will meet tomorrow to reach a conclusion on the new policy.', ko: '위원회는 새로운 정책에 대해 결정하기 위해 내일 모일 것이다.' },
      ],
    }
  ),
  word('deck', '갑판', 5, 'noun',
    ['선실', '창고', '객실', '엔진실', '조타실', '닻', '돛', '선체', '구명보트', '화물칸'],
    tips({
      etymology: '네덜란드어 \'dekken(덮다)\'에서 유래하여 배의 위를 덮고 있는 바닥을 의미하게 되었습니다.',
      visual: '호화 유람선의 탁 트인 야외 바닥에서 사람들이 일광욕을 즐기는 모습을 상상해 보세요.',
      soundAlike: '카드 한 \'댁(deck)\'을 들고 배의 \'갑판\' 위에서 게임을 하는 장면을 연상해 보세요.',
      context: '배의 층수를 나타낼 때도 쓰이며, 카드 한 세트나 집 뒤편의 나무 테라스를 지칭할 때도 자주 쓰입니다.',
      synonymAntonym: 'floor나 platform과 유사한 구조적 의미를 지니며, 배의 가장 밑바닥인 hold와는 반대되는 위치입니다.',
    }),
    {
      definition: 'A flat open surface on a ship or boat where people can walk; also a set of playing cards.',
      synonyms: ['platform', 'floor', 'terrace'],
      antonyms: ['hold', 'keel', 'bottom'],
      exampleSentences: [
        { en: 'We stood on the upper level of the ship to watch the sunset over the ocean.', ko: '우리는 바다 너머로 지는 노을을 보기 위해 배의 위쪽 갑판에 서 있었다.' },
        { en: 'He shuffled the full set of cards before dealing them to the players.', ko: '그는 플레이어들에게 나누어 주기 전에 카드 한 벌을 섞었다.' },
      ],
    }
  ),
  word('deep', '깊은', 2, 'adjective',
    ['얕은', '넓은', '좁은', '높은', '평평한', '거친', '부드러운', '단단한', '가벼운', '무거운'],
    tips({
      etymology: '고대 영어 deop에서 유래하여 바닥까지의 거리가 먼 상태를 뜻하게 되었습니다.',
      visual: '끝이 보이지 않는 캄캄하고 푸른 심해 바닷속을 상상해 보세요.',
      soundAlike: '발음이 \'딥\'이므로 소스에 \'딥(dip)\'하고 깊숙이 찍어 먹는 모습을 떠올려 보세요.',
      context: '단순히 물리적인 깊이뿐만 아니라 지식이나 감정이 심오할 때도 자주 쓰입니다.',
      synonymAntonym: 'shallow(얕은)와 반대되는 개념으로 profound(심오한)와 함께 기억하면 좋습니다.',
    }),
    {
      definition: 'extending far down from the top or surface, or being very intense in emotion or thought',
      synonyms: ['profound', 'bottomless', 'intense'],
      antonyms: ['shallow', 'superficial', 'slight'],
      exampleSentences: [
        { en: 'The divers explored the deep waters of the Pacific Ocean to find new species.', ko: '잠수부들은 새로운 종을 찾기 위해 태평양의 깊은 바다를 탐험했습니다.' },
        { en: 'He fell into a deep sleep after a long and exhausting day at work.', ko: '그는 직장에서 길고 피곤한 하루를 보낸 후 깊은 잠에 빠졌습니다.' },
      ],
    }
  ),
  word('defense', '방어', 6, 'noun',
    ['공격', '진격', '침공', '습격', '도전', '협공', '맹공', '선제', '역공', '반격'],
    tips({
      etymology: '라틴어 defendere에서 유래했으며, de(멀리)와 fendere(치다)가 합쳐져 적을 쳐서 멀리 쫓아낸다는 의미를 담고 있습니다.',
      visual: '성벽 위에서 병사들이 화살을 쏘며 적의 침입을 막아내는 든든한 요새의 모습을 상상해 보세요.',
      soundAlike: '운동 경기에서 해설자가 \'디펜스! 디펜스!\'라고 외치며 수비를 응원하는 소리를 떠올리면 쉽습니다.',
      context: '축구나 농구 같은 스포츠 경기뿐만 아니라 법정에서 피고인을 변호하는 상황에서도 자주 쓰입니다.',
      synonymAntonym: '유의어인 protection은 보호에 초점이 있고, 반의어인 offense는 득점을 위한 공격을 뜻합니다.',
    }),
    {
      definition: 'the act of protecting someone or something against attack, criticism, or danger',
      synonyms: ['protection', 'guard', 'shield'],
      antonyms: ['offense', 'attack', 'assault'],
      exampleSentences: [
        { en: 'The city built a strong wall as a primary protection against invaders.', ko: '그 도시는 침략자들에 맞서기 위한 주요 수단으로 강력한 성벽을 쌓았습니다.' },
        { en: 'The lawyer presented a compelling argument in support of the accused person.', ko: '변호사는 피고인을 옹호하기 위해 설득력 있는 논거를 제시했습니다.' },
      ],
    }
  ),
  word('defendant', '피고', 7, 'noun',
    ['원고', '검사', '판사', '변호사', '배심원', '증인', '목격자', '피해자', '당사자', '제3자'],
    tips({
      etymology: '방어하다라는 뜻의 defend에 행위자를 뜻하는 -ant가 붙어, 법정에서 자신을 방어해야 하는 사람을 뜻합니다.',
      visual: '법정 피고인석에 앉아 변호사와 함께 심각한 표정으로 재판을 받는 사람의 모습을 상상해 보세요.',
      soundAlike: '디펜던트(defendant)는 \'뒤편(디편)에 앉아\' 재판을 기다리는 피고인의 모습과 발음이 비슷합니다.',
      context: '형사 재판에서는 피고인, 민사 재판에서는 피고라고 불리며 주로 기소나 소송을 당한 측을 의미합니다.',
      synonymAntonym: '소송을 제기한 사람인 plaintiff(원고)와 정반대 입장에 서 있는 사람입니다.',
    }),
    {
      definition: 'an individual, company, or institution sued or accused in a court of law',
      synonyms: ['accused', 'litigant', 'respondent'],
      antonyms: ['plaintiff', 'accuser', 'prosecutor'],
      exampleSentences: [
        { en: 'The jury found the accused party not guilty after a lengthy trial.', ko: '배심원단은 긴 재판 끝에 피고에게 무죄 판결을 내렸습니다.' },
        { en: 'The lawyer advised his client to remain silent during the cross-examination.', ko: '변호사는 반대 심문 동안 의뢰인인 피고에게 침묵을 지키라고 조언했습니다.' },
      ],
    }
  ),
  word('deficiency', '결핍', 9, 'noun',
    ['풍부', '과잉', '충만', '충족', '넉넉', '여유', '과다', '풍부함', '충분', '잉여'],
    tips({
      etymology: '라틴어 \'deficere\'에서 유래하며, \'de(떨어져)\'와 \'facere(만들다/하다)\'가 합쳐져 필요한 만큼 만들어내지 못함을 의미합니다.',
      visual: '비타민 통이 텅 비어 있거나, 가뭄으로 인해 바닥이 갈라진 메마른 땅을 상상해 보세요.',
      soundAlike: '발음이 \'디피션시\'로 들리는데, \'뒤(de)가 피(fi)어있는(션시) 상태\' 즉, 무언가 비어있는 결핍 상태로 연상해 보세요.',
      context: '주로 영양소 부족, 예산 부족, 혹은 성격상의 결함 등을 설명할 때 자주 쓰이는 격식 있는 표현입니다.',
      synonymAntonym: '유의어인 shortage는 양적인 부족을, 반의어인 surplus는 남는 잉여 상태를 나타냅니다.',
    }),
    {
      definition: 'a state of not having enough of something that is essential or necessary',
      synonyms: ['shortage', 'scarcity', 'dearth'],
      antonyms: ['abundance', 'surplus', 'adequacy'],
      exampleSentences: [
        { en: 'A serious vitamin deficiency can lead to various health problems.', ko: '심각한 비타민 결핍은 다양한 건강 문제를 일으킬 수 있다.' },
        { en: 'The team\'s main deficiency was a lack of experienced players.', ko: '그 팀의 주요 결점은 경험 많은 선수들이 부족하다는 것이었다.' },
      ],
    }
  ),
  word('definite', '명확한', 4, 'adjective',
    ['모호한', '애매한', '불명확한', '흐릿한', '불확실한', '의심스러운', '애매모호한', '뚜렷하지 않은', '불분명한', '흔들리는'],
    tips({
      etymology: '라틴어 \'definire\'에서 유래했으며, \'de(완전히)\'와 \'finis(경계/끝)\'가 합쳐져 경계가 확실히 정해졌다는 의미를 가집니다.',
      visual: '안개가 자욱한 길을 걷다가 갑자기 안개가 걷히며 표지판이 또렷하게 보이는 장면을 상상해 보세요.',
      soundAlike: '발음이 \'데피닛\'과 유사하므로, \'대피\'할 곳이 \'명확\'하게 정해졌다고 연상해 보세요.',
      context: '확신이 서지 않는 상황이 아니라, 예나 아니오가 확실한 결정을 내릴 때 주로 쓰입니다.',
      synonymAntonym: '확실한 상태를 뜻하는 clear와 반대되는 개념인 vague를 함께 기억하면 좋습니다.',
    }),
    {
      definition: 'clearly stated or decided; not leaving any doubt or confusion',
      synonyms: ['clear-cut', 'specific', 'explicit'],
      antonyms: ['vague', 'ambiguous', 'uncertain'],
      exampleSentences: [
        { en: 'We need a definite answer by tomorrow morning to proceed with the project.', ko: '프로젝트를 진행하기 위해 내일 아침까지 명확한 답변이 필요합니다.' },
        { en: 'There is a definite improvement in your English speaking skills this month.', ko: '이번 달에 당신의 영어 회화 실력에 뚜렷한 향상이 있었습니다.' },
      ],
    }
  ),
  word('degrade', '타락시키다', 10, 'verb',
    ['승격시키다', '높이다', '존중하다', '칭송하다', '올리다', '향상시키다', '고양하다', '격려하다', '포상하다', '추대하다'],
    tips({
      etymology: '아래를 뜻하는 de-와 단계를 뜻하는 grade가 합쳐져 가치나 등급을 아래로 떨어뜨린다는 의미가 됩니다.',
      visual: '계단 아래로 굴러떨어지는 물건이나 흙탕물이 튀어 더러워진 흰 옷을 상상해 보세요.',
      soundAlike: '발음이 \'뒤로 가이드\'와 비슷하죠? 뒤로, 즉 나쁜 쪽으로 이끌어 가치를 떨어뜨린다고 기억하세요.',
      context: '환경 오염이 생태계를 파괴하거나, 누군가를 모욕하여 인격을 깎아내릴 때 주로 사용됩니다.',
      synonymAntonym: '가치를 낮추는 demean과 반대로 가치를 높이는 upgrade를 함께 외우면 효과적입니다.',
    }),
    {
      definition: 'to lower the character or quality of something; to treat someone with a lack of respect',
      synonyms: ['deteriorate', 'demean', 'debase'],
      antonyms: ['upgrade', 'enhance', 'elevate'],
      exampleSentences: [
        { en: 'Exposure to sunlight can cause the plastic to weaken and break down over time.', ko: '햇빛에 노출되면 시간이 지남에 따라 플라스틱의 질이 저하되고 분해될 수 있습니다.' },
        { en: 'The cruel comments were intended to humiliate and lower the dignity of the speaker.', ko: '그 잔인한 논평들은 화자를 굴욕 주고 인격을 타락시키려는 의도였습니다.' },
      ],
    }
  ),
  word('delete', '삭제하다', 5, 'verb',
    ['확인하다', '시작하다', '중단하다', '선택하다', '결정하다', '요청하다', '설명하다', '관리하다', '보완하다', '분석하다'],
    tips({
      etymology: '라틴어 delere에서 유래되었으며, \'지우다\' 또는 \'말살하다\'라는 의미를 담고 있습니다.',
      visual: '컴퓨터 키보드의 \'Del\' 키를 누르자마자 화면의 글자가 순식간에 사라지는 모습을 상상하세요.',
      soundAlike: '\'딜리트\' 발음이 \'뒤를 이트(잇다)\'와 비슷하지만, 반대로 뒤에 남은 흔적을 없앤다고 생각하세요.',
      context: '이메일을 잘못 보냈을 때나 불필요한 파일을 정리할 때 가장 자주 사용하는 기능입니다.',
      synonymAntonym: 'erase와 같은 유의어와 함께 외우고, 반대로 내용을 추가하는 insert와 비교해 보세요.',
    }),
    {
      definition: 'to remove written or stored information completely from a document or computer system',
      synonyms: ['erase', 'remove', 'eliminate'],
      antonyms: ['insert', 'add', 'restore'],
      exampleSentences: [
        { en: 'You should check your draft carefully before you decide to remove any paragraphs.', ko: '문단을 삭제하기로 결정하기 전에 초안을 주의 깊게 확인해야 합니다.' },
        { en: 'The system will automatically wipe all temporary files to free up storage space.', ko: '시스템은 저장 공간을 확보하기 위해 모든 임시 파일을 자동으로 삭제할 것입니다.' },
      ],
    }
  ),
  word('delicate', '섬세한', 6, 'adjective',
    ['거친', '튼튼한', '무딘', '강력한', '평범한', '단단한', '투박한', '견고한', '둔감한', '조잡한'],
    tips({
      etymology: '라틴어 \'delicatus\'에서 유래했으며, 이는 \'즐거움을 주는\' 또는 \'매혹적인\'이라는 의미를 담고 있어 정교하고 아름다운 느낌을 줍니다.',
      visual: '아주 얇은 유리잔이나 나비의 날개처럼 살짝만 건드려도 부서질 듯한 정교한 물체를 상상해 보세요.',
      soundAlike: '\'델리(deli)\'가 맛있는 음식을 뜻하듯, 아주 부드럽고 섬세한 맛을 내는 고급 요리를 떠올리면 쉽습니다.',
      context: '깨지기 쉬운 물건뿐만 아니라, 다루기 까다로운 민감한 문제나 아주 고운 피부를 표현할 때도 자주 쓰입니다.',
      synonymAntonym: 'fragile과 함께 외우면 \'부서지기 쉬운\' 느낌이 강조되고, robust와 대조하면 \'연약함\'의 의미가 명확해집니다.',
    }),
    {
      definition: 'very fine in texture or structure; easily broken or damaged',
      synonyms: ['fragile', 'exquisite', 'subtle'],
      antonyms: ['robust', 'coarse', 'strong'],
      exampleSentences: [
        { en: 'The antique vase is extremely fragile and needs careful handling.', ko: '그 골동품 화병은 매우 섬세해서 조심스러운 취급이 필요하다.' },
        { en: 'The negotiators discussed a highly sensitive issue that required a tactful approach.', ko: '협상가들은 신중한 접근이 필요한 매우 민감한 사안에 대해 논의했다.' },
      ],
    }
  ),
  word('delicious', '맛있는', 3, 'adjective',
    ['맛없는', '싱거운', '쓴', '짜다', '시다', '떫은', '역한', '무미건조한', '싫은', '불쾌한'],
    tips({
      etymology: '라틴어 \'deliciae(즐거움)\'에서 유래하여 미각적인 즐거움을 주는 상태를 뜻합니다.',
      visual: '김이 모락모락 나는 갓 구운 빵이나 가장 좋아하는 음식을 한 입 베어 무는 장면을 상상하세요.',
      soundAlike: '\'딜리셔스\'의 \'딜리\'를 \'빨리\'와 연결해 \'너무 맛있어서 빨리 먹고 싶다\'고 기억해 보세요.',
      context: '주로 음식의 맛이 훌륭할 때 쓰이지만, 향기나 기분 좋은 경험을 묘사할 때도 사용됩니다.',
      synonymAntonym: 'tasty와는 유의어 관계이며, 맛이 없거나 불쾌한 상태인 tasteless와는 반대되는 개념입니다.',
    }),
    {
      definition: 'highly pleasant to the taste or smell',
      synonyms: ['tasty', 'scrumptious', 'flavorful'],
      antonyms: ['tasteless', 'unpalatable', 'disgusting'],
      exampleSentences: [
        { en: 'The chef prepared a delicious three-course meal for the guests.', ko: '요리사는 손님들을 위해 아주 맛있는 3코스 식사를 준비했습니다.' },
        { en: 'The aroma of freshly baked cookies was absolutely wonderful.', ko: '갓 구운 쿠키의 향기는 정말이지 환상적이었습니다.' },
      ],
    }
  ),
  word('delight', '기쁘게 하다', 7, 'verb',
    ['실망시키다', '무시하다', '분석하다', '방해하다', '거절하다', '지루하게하다', '슬프게하다', '비난하다', '연기하다', '조사하다'],
    tips({
      etymology: '라틴어 delectare에서 유래되었으며, \'유혹하다\' 또는 \'매료시키다\'라는 의미가 \'큰 기쁨을 주다\'로 발전했습니다.',
      visual: '어두운 방에 갑자기 밝은 전등(light)이 켜지며 사람들의 얼굴이 환해지는 모습을 상상해 보세요.',
      soundAlike: '발음이 \'딜라이트\'이므로, 맛있는 디저트를 먹고 \'뒤(de)가 가벼워질(light) 만큼 기쁘다\'라고 연상해 보세요.',
      context: '주로 상대방을 아주 만족시키거나 예상치 못한 즐거움을 주었을 때 사용되는 긍정적인 단어입니다.',
      synonymAntonym: '기쁨을 주는 please와 반대로 불쾌감을 주는 displease를 함께 기억하면 효과적입니다.',
    }),
    {
      definition: 'To give great pleasure, satisfaction, or enjoyment to someone.',
      synonyms: ['please', 'gratify', 'enchant'],
      antonyms: ['displease', 'depress', 'offend'],
      exampleSentences: [
        { en: 'The magician\'s incredible tricks never fail to thrill and amuse the young audience.', ko: '마술사의 놀라운 기술은 어린 관객들을 항상 즐겁고 기쁘게 한다.' },
        { en: 'The chef hoped that his new signature dish would satisfy and charm every guest.', ko: '요리사는 자신의 새로운 대표 요리가 모든 손님을 기쁘게 하기를 바랐다.' },
      ],
    }
  ),
  word('democrat', '민주주의자', 4, 'noun',
    ['독재자', '권위주의자', '전제군주', '폭군', '일당독재', '과두정', '군주', '왕', '황제', '독재지지자'],
    tips({
      etymology: '민중을 뜻하는 \'demos\'와 지배를 뜻하는 \'kratos\'가 합쳐져 국민이 주인인 세상을 꿈꾸는 사람을 뜻합니다.',
      visual: '투표소에서 소중한 한 표를 행사하며 평등한 권리를 주장하는 시민의 모습을 상상해 보세요.',
      soundAlike: '발음이 \'데모크랫\'과 유사한데, 민주주의를 위해 \'데모\'를 하는 사람들의 열정을 연상하면 쉽습니다.',
      context: '정치적 담론이나 선거철 뉴스에서 평등과 자유를 중시하는 인물을 묘사할 때 자주 등장합니다.',
      synonymAntonym: '자유주의자와는 결을 같이 하지만, 모든 권력을 한 명이 쥐는 독재자와는 정반대의 개념입니다.',
    }),
    {
      definition: 'A person who believes in or supports a system of government by the whole population through elected representatives.',
      synonyms: ['republican', 'liberal', 'egalitarian'],
      antonyms: ['autocrat', 'dictator', 'tyrant'],
      exampleSentences: [
        { en: 'As a lifelong democrat, she fought tirelessly for universal suffrage and equal rights.', ko: '평생을 민주주의자로 살면서 그녀는 보통 선거권과 평등한 권리를 위해 지치지 않고 싸웠습니다.' },
        { en: 'The young activist described himself as a staunch democrat who values the voice of the people.', ko: '그 젊은 활동가는 자신을 국민의 목소리를 소중히 여기는 확고한 민주주의자라고 묘사했습니다.' },
      ],
    }
  ),
  word('demon', '악마', 5, 'noun',
    ['천사', '성인', '선인', '수호신', '요정', '정령', '신', '구원자', '성자', '선한 존재'],
    tips({
      etymology: '그리스어 \'daimon\'에서 유래했으며, 원래는 신성한 힘을 뜻했으나 점차 사악한 영적 존재를 가리키게 되었습니다.',
      visual: '머리에 뿔이 나고 꼬리가 달린 전형적인 지옥의 괴물 형상을 상상해 보세요.',
      soundAlike: '발음이 \'데몬\'이므로, 컴퓨터 화면을 가득 채운 \'데몬\' 툴 아이콘이나 게임 속 몬스터를 떠올리면 쉽습니다.',
      context: '주로 판타지 소설이나 종교적 문맥에서 초자연적인 악의 세력을 묘사할 때 사용됩니다.',
      synonymAntonym: '선한 존재인 angel과는 정반대의 성질을 가진 사악한 존재입니다.',
    }),
    {
      definition: 'an evil supernatural being often associated with hell and suffering',
      synonyms: ['devil', 'fiend', 'monster'],
      antonyms: ['angel', 'saint', 'cherub'],
      exampleSentences: [
        { en: 'The ancient legend tells of a hero who banished a powerful underworld creature to save the village.', ko: '고대 전설은 마을을 구하기 위해 강력한 지하 세계의 존재를 추방한 영웅에 대해 이야기합니다.' },
        { en: 'He fought against his inner spirits to overcome his addiction and regain control of his life.', ko: '그는 중독을 극복하고 삶의 주도권을 되찾기 위해 내면의 고통스러운 존재들과 싸웠습니다.' },
      ],
    }
  ),
  word('dentist', '치과의사', 1, 'noun',
    ['내과의사', '외과의사', '간호사', '약사', '수의사', '한의사', '물리치료사', '정신과의사', '소아과의사', '안과의사'],
    tips({
      etymology: '라틴어 \'dens(치아)\'에서 유래했습니다. \'dent\'가 들어간 단어는 치아와 관련이 깊습니다.',
      visual: '하얀 가운을 입고 마스크를 쓴 채 밝은 조명 아래에서 입안을 살피는 의사를 떠올려 보세요.',
      soundAlike: '\'덴티스트\'에서 \'덴\'을 \'단단한\' 치아의 느낌과 연결해 발음해 보세요.',
      context: '정기 검진을 받거나 충치가 생겼을 때 병원을 방문하는 상황에서 주로 쓰입니다.',
      synonymAntonym: '치아 전문가인 dental surgeon과 유사하며, 환자인 patient와는 반대되는 관계입니다.',
    }),
    {
      definition: 'A medical professional who is trained to care for and repair people\'s teeth and gums.',
      synonyms: ['dental surgeon', 'orthodontist', 'tooth doctor'],
      antonyms: ['patient', 'layperson', 'client'],
      exampleSentences: [
        { en: 'I have an appointment with the specialist to get my wisdom tooth pulled out.', ko: '나는 사랑니를 뽑기 위해 치과 의사와 예약이 되어 있다.' },
        { en: 'Children should visit the clinic twice a year for a regular checkup.', ko: '아이들은 정기 검진을 위해 일 년에 두 번 치과 의사를 방문해야 한다.' },
      ],
    }
  ),
  word('deny', '부정하다', 6, 'verb',
    ['인정하다', '수용하다', '허가하다', '고백하다', '동의하다', '확인하다', '증명하다', '수락하다', '지지하다', '발표하다'],
    tips({
      etymology: '라틴어 \'denegare\'에서 유래했으며, \'de-\'(완전히)와 \'negare\'(아니라고 말하다)가 합쳐져 강하게 부정한다는 의미를 가집니다.',
      visual: '법정에서 피고인이 검사의 질문에 고개를 가로저으며 \'아니오\'라고 외치는 장면을 상상해 보세요.',
      soundAlike: '\'디나이\' 발음이 \'뒤나이(뒤로 나자빠지다)\'와 비슷하죠? 사실이 아니라고 뒤로 물러서며 거절하는 모습을 떠올려 보세요.',
      context: '뉴스에서 정치인이 혐의를 부인하거나, 누군가 비밀을 말해달라는 요청을 거절할 때 자주 쓰입니다.',
      synonymAntonym: '사실을 거부하는 reject와 유의어이며, 사실임을 인정하는 admit과는 반대되는 관계입니다.',
    }),
    {
      definition: 'to state that a statement is untrue or to refuse to admit the truth of something',
      synonyms: ['refute', 'reject', 'contradict'],
      antonyms: ['admit', 'confess', 'acknowledge'],
      exampleSentences: [
        { en: 'The suspect continued to refuse the allegations even after the evidence was presented.', ko: '용의자는 증거가 제시된 후에도 혐의를 계속해서 부인했다.' },
        { en: 'It is impossible to ignore the fact that global temperatures are rising.', ko: '지구의 기온이 상승하고 있다는 사실을 부정하는 것은 불가능하다.' },
      ],
    }
  ),
  word('department', '부서', 7, 'noun',
    ['본사', '지사', '협력업체', '이사회', '주식회사', '개인사업자', '노동조합', '고객센터', '물류창고', '비서실'],
    tips({
      etymology: '라틴어 \'departire(나누다)\'에서 유래하여, 큰 조직을 기능별로 \'나눈 구역\'을 의미합니다.',
      visual: '회사 건물의 층별 안내도에서 마케팅부, 인사부 등으로 칸칸이 나누어진 사무실 풍경을 상상해 보세요.',
      soundAlike: '발음이 \'디파트먼트\'이므로, 백화점(Department Store)의 각 층별 매장 구분을 떠올리면 쉽습니다.',
      context: '비즈니스 환경에서 특정 업무를 전담하는 조직 단위를 지칭할 때 가장 흔히 쓰이는 단어입니다.',
      synonymAntonym: 'division이나 unit과 유사하며, 조직 전체를 뜻하는 whole organization과는 반대되는 개념입니다.',
    }),
    {
      definition: 'A specialized division or branch within a large organization, such as a government, university, or business.',
      synonyms: ['division', 'section', 'unit'],
      antonyms: ['entirety', 'whole', 'totality'],
      exampleSentences: [
        { en: 'She was recently promoted to head of the marketing division.', ko: '그녀는 최근 마케팅 부서의 책임자로 승진했습니다.' },
        { en: 'Each branch of the university has its own budget and staff.', ko: '대학교의 각 학과는 자체 예산과 직원을 보유하고 있습니다.' },
      ],
    }
  ),
  word('departure', '출발', 4, 'noun',
    ['도착', '귀환', '복귀', '입장', '진입', '체류', '대기', '정지', '멈춤', '종료'],
    tips({
      etymology: '라틴어 \'de-\'(멀리)와 \'partire\'(나누다, 떠나다)가 합쳐져 원래 있던 곳에서 멀어지는 행위를 뜻합니다.',
      visual: '공항 전광판의 \'Departures\' 글자 아래로 비행기가 활주로를 박차고 오르는 모습을 상상해 보세요.',
      soundAlike: '\'디파처\'라고 발음하며, \'뒤(de)를 파(par)하고 처(ture) 나간다\'는 느낌으로 출발의 이미지를 연상하세요.',
      context: '여행의 시작뿐만 아니라, 기존의 방식이나 계획에서 벗어나는 새로운 시도를 말할 때도 자주 쓰입니다.',
      synonymAntonym: '도착을 뜻하는 arrival과 반대 개념이며, 떠남을 뜻하는 leaving과 비슷한 맥락에서 사용됩니다.',
    }),
    {
      definition: 'The action of leaving a place, especially to start a journey to another location.',
      synonyms: ['exit', 'withdrawal', 'exodus'],
      antonyms: ['arrival', 'entrance', 'stay'],
      exampleSentences: [
        { en: 'The flight\'s scheduled time of leaving was delayed by two hours due to heavy snow.', ko: '폭설로 인해 비행기의 예정된 출발 시간이 2시간 지연되었습니다.' },
        { en: 'Her sudden decision to quit the job was a significant change from her original career plan.', ko: '그녀가 직장을 그만두기로 한 갑작스러운 결정은 원래의 경력 계획에서 크게 벗어난 것이었습니다.' },
      ],
    }
  ),
  word('dependence', '의존', 5, 'noun',
    ['독립', '자립', '자주', '자유', '해방', '탈피', '무의존', '자급', '단독', '고립'],
    tips({
      etymology: '라틴어 \'dependere\'에서 유래하며, \'de(아래로)\'와 \'pendere(매달리다)\'가 합쳐져 누군가에게 매달려 있는 상태를 뜻합니다.',
      visual: '갓난아기가 엄마의 손을 꼭 잡고 매달려 있는 모습을 상상해 보세요.',
      soundAlike: '발음이 \'디펜던스\'이므로, 누군가에게 \'기댄다(디)\'는 느낌으로 연결해 보세요.',
      context: '경제적 자립이나 약물 중독, 혹은 타인에 대한 심리적 기댐을 표현할 때 자주 쓰입니다.',
      synonymAntonym: 'reliance와 유의어 관계이며, 반대말인 independence(독립)와 함께 외우면 효과적입니다.',
    }),
    {
      definition: 'the state of needing someone or something for aid, support, or survival',
      synonyms: ['reliance', 'addiction', 'subservience'],
      antonyms: ['independence', 'autonomy', 'self-sufficiency'],
      exampleSentences: [
        { en: 'The country is trying to reduce its heavy dependence on foreign oil.', ko: '그 나라는 외국산 석유에 대한 과도한 의존도를 줄이려 노력하고 있다.' },
        { en: 'Mutual dependence is a key factor in a successful long-term relationship.', ko: '상호 의존은 성공적인 장기적 관계의 핵심 요소이다.' },
      ],
    }
  ),
  word('depress', '우울하게 하다', 6, 'verb',
    ['고무시키다', '격려하다', '상승시키다', '축하하다', '확장하다', '가속하다', '성공하다', '승인하다', '발생하다', '해결하다'],
    tips({
      etymology: '아래로를 뜻하는 de-와 누르다를 뜻하는 press가 합쳐져 마음을 아래로 짓누른다는 의미가 됩니다.',
      visual: '어깨가 축 늘어진 사람이 무거운 바위에 짓눌려 있는 모습을 상상해 보세요.',
      soundAlike: '발음이 \'뒤를 눌렀으\'와 비슷하죠? 기분이 뒤로 처지게 꾹 누르는 상황을 떠올려 보세요.',
      context: '경제 상황이 안 좋을 때 경기를 침체시키거나, 물리적으로 버튼을 아래로 누를 때도 사용합니다.',
      synonymAntonym: '기운을 북돋아 주는 cheer up이나 uplift와는 정반대의 감정 상태를 나타냅니다.',
    }),
    {
      definition: 'to make someone feel unhappy and without hope, or to lower the level or value of something',
      synonyms: ['sadden', 'discourage', 'dishearten'],
      antonyms: ['encourage', 'cheer', 'uplift'],
      exampleSentences: [
        { en: 'The rainy weather and grey skies tend to lower my mood and make me feel sad.', ko: '비 오는 날씨와 회색빛 하늘은 내 기분을 저하시키고 우울하게 만드는 경향이 있다.' },
        { en: 'Bad news about the economy can often discourage potential investors.', ko: '경제에 관한 나쁜 소식은 종종 잠재적 투자자들을 낙담시키고 경기를 침체시킬 수 있다.' },
      ],
    }
  ),
  word('descend', '내려가다', 7, 'verb',
    ['오르다', '상승하다', '올라가다', '등반하다', '뛰어오르다', '급상승하다', '치솟다', '솟다', '올라서다', '승진하다'],
    tips({
      etymology: '라틴어 \'de-\'(아래로)와 \'scandere\'(사다리를 타다)가 결합되어 아래로 내려간다는 의미가 되었습니다.',
      visual: '비행기가 착륙을 위해 구름 아래로 서서히 고도를 낮추는 장면을 상상해 보세요.',
      soundAlike: '\'디센드\' 발음이 \'뒤(de)로 샌다(scend)\'와 비슷하죠? 뒤로 미끄러져 내려가는 모습을 떠올려 보세요.',
      context: '산 정상에서 하산하거나, 계단을 내려올 때, 혹은 기온이 떨어질 때 주로 사용됩니다.',
      synonymAntonym: '위로 올라가는 ascend와 아래로 내려가는 descend를 짝지어 반대 방향으로 기억하세요.',
    }),
    {
      definition: 'to move from a higher level to a lower one',
      synonyms: ['drop', 'sink', 'plummet'],
      antonyms: ['ascend', 'climb', 'rise'],
      exampleSentences: [
        { en: 'The hikers began to slowly move down the mountain as the sun started to set.', ko: '해가지기 시작하자 등산객들은 천천히 산을 내려가기 시작했다.' },
        { en: 'The aircraft will start to lower its altitude for landing in ten minutes.', ko: '항공기는 10분 후에 착륙을 위해 고도를 낮추기 시작할 것이다.' },
      ],
    }
  ),
  word('description', '설명', 4, 'noun',
    ['침묵', '생략', '축약', '암시', '힌트', '요약', '제목', '목록', '표', '도표'],
    tips({
      etymology: '라틴어 \'de(아래로)\'와 \'scribere(쓰다)\'가 합쳐져, 대상을 종이 위에 써 내려가며 묘사한다는 의미에서 유래했습니다.',
      visual: '경찰이 목격자의 진술을 토대로 범인의 몽타주를 그리기 위해 세부 사항을 받아 적는 장면을 상상해 보세요.',
      soundAlike: '디스크립션(description) - \'디테일하게 써(scrip) 놓은 것\'이라고 소리 내어 읽으며 암기하면 쉽습니다.',
      context: '제품을 구매할 때 상세 페이지에 적힌 제품의 특징이나 외관에 대한 서술 부분을 떠올려 보세요.',
      synonymAntonym: '무언가를 자세히 설명하는 explanation과 반대로 아무것도 말하지 않는 silence를 함께 기억하세요.',
    }),
    {
      definition: 'a detailed statement or account that gives a mental image of something using words',
      synonyms: ['explanation', 'depiction', 'portrayal'],
      antonyms: ['concealment', 'silence', 'distortion'],
      exampleSentences: [
        { en: 'The witness provided a detailed account of the suspect to the police officer.', ko: '목격자는 경찰관에게 용의자에 대한 상세한 묘사를 제공했습니다.' },
        { en: 'Please read the product information carefully before making a purchase.', ko: '구매하기 전에 제품 설명을 주의 깊게 읽어주시기 바랍니다.' },
      ],
    }
  ),
  word('desert', '사막', 5, 'noun',
    ['오아시스', '밀림', '숲', '초원', '습지', '호수', '강', '해안', '산림', '녹지'],
    tips({
      etymology: '라틴어 desertus(버려진)에서 유래하여, 사람이 살지 않는 황량한 땅을 의미합니다.',
      visual: '끝없이 펼쳐진 모래 언덕과 뜨거운 태양 아래 선인장만 있는 풍경을 상상해 보세요.',
      soundAlike: '식후에 먹는 디저트(dessert)와 철자가 비슷하지만, 사막은 s가 하나뿐이라 휑하다고 기억하세요.',
      context: '강수량이 매우 적고 식물이 자라기 힘든 건조한 지역을 설명할 때 주로 쓰입니다.',
      synonymAntonym: '황무지를 뜻하는 wasteland와 반대되는 개념인 비옥한 땅 fertile land를 함께 익혀두세요.',
    }),
    {
      definition: 'A large, extremely dry area of land with very little vegetation, usually covered with sand.',
      synonyms: ['wasteland', 'wilderness', 'arid region'],
      antonyms: ['wetland', 'rainforest', 'oasis'],
      exampleSentences: [
        { en: 'The nomads traveled across the vast Sahara for many weeks.', ko: '유목민들은 몇 주 동안 광활한 사하라 사막을 가로질러 여행했습니다.' },
        { en: 'Many unique animals have adapted to survive in the harsh conditions of the dry terrain.', ko: '많은 독특한 동물들이 건조한 지형의 가혹한 환경에서 살아남기 위해 적응해 왔습니다.' },
      ],
    }
  ),
  word('deserve', '받을 만하다', 6, 'verb',
    ['요청하다', '설명하다', '관리하다', '보완하다', '분석하다', '정리하다', '적용하다', '반복하다', '행동하다', '수행하다'],
    tips({
      etymology: '라틴어 deservire에서 유래했으며, de(완전히)와 servire(봉사하다)가 합쳐져 \'충분히 봉사했기에 보상을 받을 자격이 있다\'는 의미가 되었습니다.',
      visual: '열심히 훈련한 선수가 금메달을 목에 걸고 환하게 웃는 시상대 위의 모습을 상상해 보세요.',
      soundAlike: '발음이 \'디저브\'와 유사하므로, 맛있는 \'디저트(dessert)\'를 먹을 자격이 충분하다고 연상하면 쉽습니다.',
      context: '주로 칭찬, 벌, 보상, 기회 등 어떤 결과에 대해 그럴 만한 가치가 있음을 나타낼 때 사용합니다.',
      synonymAntonym: 'merit와 유사한 의미를 지니며, 부적절하거나 자격이 없는 상태를 뜻하는 fail과는 반대되는 개념입니다.',
    }),
    {
      definition: 'to be worthy of reward, punishment, or attention based on one\'s actions or qualities',
      synonyms: ['merit', 'warrant', 'earn'],
      antonyms: ['fail', 'lose', 'forfeit'],
      exampleSentences: [
        { en: 'After working overtime for a month, you truly a break.', ko: '한 달 동안 야근을 했으니 당신은 정말로 휴식을 취할 자격이 있습니다.' },
        { en: 'Every child should have the opportunity to get the education they need.', ko: '모든 아이들은 그들에게 필요한 교육을 받을 권리가 있습니다.' },
      ],
    }
  ),
  word('despair', '절망하다', 7, 'verb',
    ['희망하다', '기뻐하다', '성공하다', '신뢰하다', '만족하다', '도전하다', '안심하다', '축하하다', '기대하다', '인내하다'],
    tips({
      etymology: '라틴어 \'desperare\'에서 유래했으며, \'de-\'(반대/부정)와 \'spes\'(희망)가 결합되어 희망이 완전히 사라진 상태를 뜻합니다.',
      visual: '어두운 낭떠러지 끝에 혼자 앉아 고개를 숙이고 있는 사람의 뒷모습을 상상해 보세요.',
      soundAlike: '\'디스-페어\' 발음이 \'이 판은 다 패(paire)했다\'라고 자포자기하며 말하는 소리와 비슷하다고 연결해 보세요.',
      context: '주로 감당하기 힘든 불행이나 실패를 겪었을 때, 더 이상 나아질 기미가 보이지 않는 심각한 상황에서 쓰입니다.',
      synonymAntonym: '희망을 버린다는 뜻의 lose hope와 유의어이며, 반대로 희망을 품는 hope와는 정반대의 감정입니다.',
    }),
    {
      definition: 'to lose all confidence that a situation will improve or that you will succeed',
      synonyms: ['lose hope', 'give up', 'surrender'],
      antonyms: ['hope', 'trust', 'believe'],
      exampleSentences: [
        { en: 'The team began to lose heart and feel a sense of hopelessness after their third consecutive defeat.', ko: '팀은 3연패 이후 낙담하며 절망하기 시작했다.' },
        { en: 'Do not give up even when things seem at their worst; there is always a way out.', ko: '상황이 최악으로 보일 때라도 절망하지 마세요. 항상 탈출구는 있습니다.' },
      ],
    }
  ),
  word('desperate', '절망적인', 4, 'adjective',
    ['희망찬', '낙관적인', '평온한', '만족스러운', '부유한', '성공적인', '안정된', '침착한', '자신만만한', '여유로운'],
    tips({
      etymology: '라틴어 desperare에서 유래되었으며, \'de(분리/부정)\'와 \'sperare(희망하다)\'가 합쳐져 희망이 완전히 사라진 상태를 뜻합니다.',
      visual: '벼랑 끝에 매달려 마지막 밧줄을 잡으려고 애쓰는 사람의 절박한 표정을 상상해 보세요.',
      soundAlike: '발음이 \'데스퍼릿\'과 유사한데, 죽음(Death)이 눈앞에 닥친 것처럼 절박하고 위험한 상황을 연상하면 쉽습니다.',
      context: '경제적 위기나 구조 요청처럼 수단과 방법을 가리지 않고 해결책을 찾아야만 하는 극단적인 상황에서 주로 쓰입니다.',
      synonymAntonym: '희망이 없는 hopeless와 유사하며, 반대로 모든 것이 안정적이고 평화로운 calm과는 대조를 이룹니다.',
    }),
    {
      definition: 'feeling, showing, or involving a hopeless sense that a situation is so extremely bad as to be impossible to deal with',
      synonyms: ['hopeless', 'frantic', 'drastic'],
      antonyms: ['hopeful', 'cheerful', 'composed'],
      exampleSentences: [
        { en: 'The survivors were in a hopeless situation and made a final, frantic attempt to call for help.', ko: '생존자들은 절망적인 상황에 처해 있었고 도움을 요청하기 위해 마지막으로 필사적인 시도를 했습니다.' },
        { en: 'As the deadline approached, he became increasingly anxious to find a solution to the problem.', ko: '마감 기한이 다가오자 그는 문제에 대한 해결책을 찾기 위해 점점 더 절박해졌습니다.' },
      ],
    }
  ),
  word('despite', '~에도 불구하고', 5, 'preposition',
    ['덕분에', '때문에', '덕택에', '결과적으로', '이유로', '덕분', '덕에', '감사하게도', '따라서', '말미암아'],
    tips({
      etymology: '라틴어 despicere에서 유래하여 누군가를 멸시하거나 무시한다는 뜻에서 \'장애물을 무시하고\'라는 의미로 발전했습니다.',
      visual: '거센 비바람이 몰아치는 날씨에도 굴하지 않고 꿋꿋하게 산을 오르는 등산객의 모습을 상상해 보세요.',
      soundAlike: '디스(dis)하는 파이트(pight) 상황에서도 굴하지 않고 자기 갈 길을 가는 모습을 연상해 보세요.',
      context: '역경이나 반대되는 상황이 앞에 언급되었음에도 불구하고 뒤에 긍정적이거나 의외의 결과가 나올 때 주로 쓰입니다.',
      synonymAntonym: 'in spite of와 같은 의미로 쓰이며, 반대로 원인과 결과를 나타내는 because of와 대조됩니다.',
    }),
    {
      definition: 'without being affected by the factors or circumstances mentioned',
      synonyms: ['notwithstanding', 'regardless of', 'even with'],
      antonyms: ['because of', 'due to', 'owing to'],
      exampleSentences: [
        { en: 'The outdoor concert continued even more energetically despite the heavy rain.', ko: '폭우에도 불구하고 야외 콘서트는 더욱 활기차게 계속되었습니다.' },
        { en: 'She managed to finish the marathon despite her painful ankle injury.', ko: '그녀는 발목 부상의 통증에도 불구하고 마라톤을 완주해냈습니다.' },
      ],
    }
  ),
  word('destination', '목적지', 6, 'noun',
    ['출발지', '경유지', '중간지점', '회귀선', '출발점', '정거장', '대기실', '안내소', '매표소', '교차로'],
    tips({
      etymology: '라틴어 \'destinare\'에서 유래하여 \'단단히 고정하다\' 혹은 \'결정하다\'라는 의미가 끝 지점으로 굳어진 것입니다.',
      visual: '비행기 티켓에 적힌 도착 도시 이름 위에 커다란 깃발이 꽂혀 있는 모습을 상상해 보세요.',
      soundAlike: '\'데스티네이션\'의 \'데스(Des)\'를 \'대(다)\'로 생각해서 \'배를 대는 곳\' 즉 목적지로 연상해 보세요.',
      context: '여행 계획을 세울 때 가장 먼저 정해야 하는 최종 도착지를 말할 때 주로 쓰입니다.',
      synonymAntonym: '도착지인 goal과 반대되는 개념인 출발점 origin을 함께 기억하면 좋습니다.',
    }),
    {
      definition: 'The ultimate location or end point where a person is traveling or where something is being sent.',
      synonyms: ['endpoint', 'goal', 'terminus'],
      antonyms: ['origin', 'source', 'start'],
      exampleSentences: [
        { en: 'After ten hours of driving, we finally reached our holiday spot in the mountains.', ko: '10시간의 운전 끝에 우리는 마침내 산속에 있는 휴가 목적지에 도착했다.' },
        { en: 'The package was redirected because the address of the final location was incorrect.', ko: '최종 목적지의 주소가 잘못되어 소포가 다시 발송되었다.' },
      ],
    }
  ),
  word('destruction', '파괴', 7, 'noun',
    ['건설', '보존', '수리', '복구', '재건', '보호', '유지', '복원', '창조', '제작'],
    tips({
      etymology: '라틴어 \'destruere\'에서 유래하며, de(반대)와 struere(쌓다)가 합쳐져 쌓아 올린 것을 무너뜨린다는 의미를 가집니다.',
      visual: '거대한 건물이 폭발하며 먼지와 함께 무너져 내리는 폐허의 현장을 상상해 보세요.',
      soundAlike: '\'디스트럭션\' 발음이 무언가를 \'뒤흔들어\' 다 부숴버리는 강한 충격음처럼 느껴집니다.',
      context: '전쟁, 자연재해, 혹은 환경 오염으로 인해 무언가가 완전히 망가졌을 때 주로 사용됩니다.',
      synonymAntonym: '무너뜨리는 ruin과 다시 세우는 construction을 대조하여 기억하면 효과적입니다.',
    }),
    {
      definition: 'the act or process of damaging something so badly that it no longer exists or cannot be repaired',
      synonyms: ['demolition', 'devastation', 'ruination'],
      antonyms: ['construction', 'creation', 'preservation'],
      exampleSentences: [
        { en: 'The hurricane left a path of widespread damage and total ruin across the coastal city.', ko: '허리케인은 해안 도시 전역에 광범위한 피해와 완전한 파괴의 흔적을 남겼습니다.' },
        { en: 'We must take immediate action to prevent the further loss of our natural rainforests.', ko: '우리는 천연 열대우림의 추가적인 파괴를 막기 위해 즉각적인 조치를 취해야 합니다.' },
      ],
    }
  ),
  word('detach', '분리하다', 4, 'verb',
    ['부착하다', '연결하다', '결합하다', '고정하다', '포함하다', '조립하다', '수집하다', '동반하다', '유지하다', '혼합하다'],
    tips({
      etymology: '프랑스어 \'des-(분리)\'와 \'tacher(붙이다)\'가 합쳐져 \'붙어 있는 것을 떼어내다\'라는 의미가 되었습니다.',
      visual: '냉장고에 붙은 포스트잇을 손가락으로 살짝 떼어내는 모습을 상상해 보세요.',
      soundAlike: '발음이 \'디태치\'이므로, \'뒤(de)를 떼지(tach)\'라고 연상하면 기억하기 쉽습니다.',
      context: '영수증 하단의 절취선을 따라 종이를 떼어내거나, 기계에서 부품을 분리할 때 주로 사용합니다.',
      synonymAntonym: '붙이는 attach와 떼어내는 detach를 세트로 외우면 반대 개념을 확실히 잡을 수 있습니다.',
    }),
    {
      definition: 'to disconnect or separate something from a larger object or group',
      synonyms: ['disconnect', 'separate', 'disengage'],
      antonyms: ['attach', 'connect', 'fasten'],
      exampleSentences: [
        { en: 'Please detach the coupon along the dotted line before using it.', ko: '사용하기 전에 점선을 따라 쿠폰을 분리해 주세요.' },
        { en: 'It is possible to detach the keyboard from this tablet computer.', ko: '이 태블릿 컴퓨터에서 키보드를 분리하는 것이 가능합니다.' },
      ],
    }
  ),
  word('devil', '악마', 5, 'noun',
    ['천사', '성인', '선인', '수호신', '요정', '신', '구원자', '성자', '선한 영', '가디언'],
    tips({
      etymology: '그리스어 \'diabolos\'에서 유래했으며, \'비방하는 자\' 또는 \'중상모략하는 자\'라는 의미를 담고 있습니다.',
      visual: '머리에 뿔이 나고 삼지창을 든 채 붉은 불길 속에 서 있는 사악한 존재의 형상을 상상해 보세요.',
      soundAlike: '발음이 \'데블\'과 유사한데, 나쁜 짓을 저지르는 \'데빌(대빌)\'런 같은 악당을 떠올리면 쉽습니다.',
      context: '종교적 문맥에서는 절대적인 악의 화신을 뜻하며, 일상에서는 매우 잔인하거나 사악한 사람을 비유할 때 씁니다.',
      synonymAntonym: '선함의 상징인 angel과는 정반대되는 사악한 존재인 demon이나 fiend를 함께 기억하세요.',
    }),
    {
      definition: 'the most powerful spirit of evil in many religions, or a very cruel and wicked person',
      synonyms: ['demon', 'fiend', 'satan'],
      antonyms: ['angel', 'saint', 'god'],
      exampleSentences: [
        { en: 'In many folk tales, the protagonist must outsmart a cunning supernatural being to save their soul.', ko: '많은 민담에서 주인공은 자신의 영혼을 구하기 위해 영리하고 초자연적인 악한 존재보다 한 수 앞서야 합니다.' },
        { en: 'He was described as a cruel man who treated his workers with the heart of a monster.', ko: '그는 노동자들을 괴물의 마음으로 대하는 잔인한 사람으로 묘사되었습니다.' },
      ],
    }
  ),
  word('devise', '고안하다', 6, 'verb',
    ['선택하다', '결정하다', '요청하다', '설명하다', '관리하다', '보완하다', '분석하다', '정리하다', '적용하다', '반복하다'],
    tips({
      etymology: '라틴어 \'dividere(나누다)\'에서 유래하여, 문제를 나누어 분석하고 해결책을 \'짜내다\'라는 의미로 발전했습니다.',
      visual: '복잡한 기계 도면을 책상 위에 펼쳐놓고 새로운 장치를 설계하는 발명가의 모습을 상상해 보세요.',
      soundAlike: '발음이 \'디바이스(device, 장치)\'와 비슷합니다. 새로운 장치(device)를 만들기 위해 계획을 \'고안하다(devise)\'라고 연결하세요.',
      context: '주로 새로운 방법, 전략, 시스템 또는 복잡한 계획을 머리를 써서 만들어낼 때 자주 쓰입니다.',
      synonymAntonym: '무언가를 만들어내는 create와 비슷하지만, 단순히 멈추는 stop과는 반대되는 개념입니다.',
    }),
    {
      definition: 'to invent a new way of doing something or a new system through careful thought',
      synonyms: ['contrive', 'formulate', 'concoct'],
      antonyms: ['destroy', 'disorganize', 'ruin'],
      exampleSentences: [
        { en: 'The engineers managed to devise a more efficient method for recycling plastic waste.', ko: '엔지니어들은 플라스틱 폐기물을 재활용하기 위한 더 효율적인 방법을 고안해냈다.' },
        { en: 'We need to devise a clever strategy to win the market share from our competitors.', ko: '우리는 경쟁사들로부터 시장 점유율을 뺏어오기 위해 영리한 전략을 짜내야 한다.' },
      ],
    }
  ),
  word('diabetes', '당뇨병', 8, 'noun',
    ['고혈압', '심장병', '신부전', '췌장염', '저혈당', '갑상선', '동맥경화', '백내장', '비만', '빈혈'],
    tips({
      etymology: '그리스어 \'diabainein\'에서 유래했으며, \'통과하다\'라는 뜻으로 체내 수분이 조절되지 않고 빠져나가는 증상을 묘사합니다.',
      visual: '혈관 속에 설탕 알갱이가 가득 차 있고, 췌장이 힘들어하는 모습을 상상해 보세요.',
      soundAlike: '\'다이아(dia) 비(be) 티스(tes)\' - 다이아몬드처럼 귀한 몸을 관리하지 않으면 비(B)급 상태가 된다고 연상하세요.',
      context: '주로 인슐린 분비나 혈당 조절 문제와 관련된 의학적 진단 상황에서 자주 등장합니다.',
      synonymAntonym: '유사한 대사 질환인 hyperglycemia와 함께 기억하고, 건강한 상태인 wellness와 대비됩니다.',
    }),
    {
      definition: 'A medical condition characterized by high levels of sugar in the blood because the body cannot produce or use insulin effectively.',
      synonyms: ['hyperglycemia', 'sugar sickness', 'metabolic disorder'],
      antonyms: ['healthiness', 'physical fitness', 'wellness'],
      exampleSentences: [
        { en: 'Patients with this condition must monitor their blood sugar levels daily.', ko: '이 질환을 앓는 환자들은 매일 혈당 수치를 점검해야 합니다.' },
        { en: 'A balanced diet and regular exercise are crucial for managing chronic metabolic illnesses.', ko: '균형 잡힌 식단과 규칙적인 운동은 만성 대사 질환을 관리하는 데 필수적입니다.' },
      ],
    }
  ),
  word('dialogue', '대화', 2, 'noun',
    ['독백', '침묵', '일방통행', '연설', '선언', '공지', '문서', '편지', '보고서', '명령'],
    tips({
      etymology: '그리스어 \'dia(사이에)\'와 \'logos(말)\'가 합쳐져 사람들 사이에 오가는 말을 뜻합니다.',
      visual: '두 명의 배우가 무대 위에서 서로 마주 보며 대본을 주고받는 장면을 상상해 보세요.',
      soundAlike: '\'다이얼로그\'는 전화기의 \'다이얼\'을 돌려 상대방과 대화하는 상황과 연결하면 쉽습니다.',
      context: '정치적 갈등이나 갈등 상황에서 평화적인 해결을 위해 소통이 필요할 때 자주 쓰입니다.',
      synonymAntonym: '혼자 말하는 monologue와 대조되며, conversation과는 비슷한 의미로 쓰입니다.',
    }),
    {
      definition: 'A formal or informal exchange of ideas or opinions between two or more people.',
      synonyms: ['conversation', 'discourse', 'chat'],
      antonyms: ['monologue', 'silence', 'soliloquy'],
      exampleSentences: [
        { en: 'The two countries have finally opened a constructive dialogue to resolve the conflict.', ko: '두 나라는 갈등을 해결하기 위해 마침내 건설적인 대화를 시작했다.' },
        { en: 'The movie was praised for its realistic and witty dialogue between the main characters.', ko: '그 영화는 주인공들 사이의 사실적이고 재치 있는 대사로 찬사를 받았다.' },
      ],
    }
  ),
];
